/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lumen;

import javax.swing.JFrame;

/**
 *
 * @author Hanse
 */
public class HelpFile extends javax.swing.JFrame {

    /**
     * Creates new form HelpFile
     */
    public HelpFile() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpSidebar = new javax.swing.JPanel();
        about = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        wotd = new javax.swing.JLabel();
        wotdLabel = new javax.swing.JLabel();
        helpLabel = new javax.swing.JLabel();
        aboutLabel = new javax.swing.JLabel();
        sideBar = new javax.swing.JLabel();
        helpMainPanel = new javax.swing.JPanel();
        howToTranslate = new javax.swing.JLabel();
        howToDefine = new javax.swing.JLabel();
        burgerIcon = new javax.swing.JLabel();
        helpBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lumen");
        setMaximumSize(new java.awt.Dimension(1540, 840));
        setMinimumSize(new java.awt.Dimension(1540, 840));
        setPreferredSize(new java.awt.Dimension(1540, 840));
        setResizable(false);
        setSize(new java.awt.Dimension(1540, 840));
        getContentPane().setLayout(null);

        helpSidebar.setMaximumSize(new java.awt.Dimension(380, 740));
        helpSidebar.setLayout(null);

        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about.png"))); // NOI18N
        about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        helpSidebar.add(about);
        about.setBounds(30, 270, 56, 56);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help.png"))); // NOI18N
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpSidebar.add(help);
        help.setBounds(30, 164, 56, 56);

        wotd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wotd.png"))); // NOI18N
        wotd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wotd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wotdMouseClicked(evt);
            }
        });
        helpSidebar.add(wotd);
        wotd.setBounds(30, 50, 56, 56);

        wotdLabel.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        wotdLabel.setForeground(new java.awt.Color(255, 255, 255));
        wotdLabel.setText("Word of the Day");
        wotdLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wotdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wotdLabelMouseClicked(evt);
            }
        });
        helpSidebar.add(wotdLabel);
        wotdLabel.setBounds(120, 60, 180, 30);

        helpLabel.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        helpLabel.setForeground(new java.awt.Color(255, 255, 255));
        helpLabel.setText("Help");
        helpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpSidebar.add(helpLabel);
        helpLabel.setBounds(120, 176, 50, 30);

        aboutLabel.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setText("About");
        aboutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
        });
        helpSidebar.add(aboutLabel);
        aboutLabel.setBounds(120, 290, 70, 20);

        sideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3. Help Sidebar.png"))); // NOI18N
        helpSidebar.add(sideBar);
        sideBar.setBounds(0, 0, 380, 740);

        getContentPane().add(helpSidebar);
        helpSidebar.setBounds(0, 100, 380, 740);

        helpMainPanel.setMaximumSize(new java.awt.Dimension(1540, 840));
        helpMainPanel.setMinimumSize(new java.awt.Dimension(1540, 840));
        helpMainPanel.setPreferredSize(new java.awt.Dimension(1540, 840));
        helpMainPanel.setLayout(null);

        howToTranslate.setFont(new java.awt.Font("Fira Sans", 0, 34)); // NOI18N
        howToTranslate.setForeground(new java.awt.Color(255, 255, 255));
        howToTranslate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        howToTranslate.setText("How to use Translate?");
        howToTranslate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        howToTranslate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                howToTranslateMouseClicked(evt);
            }
        });
        helpMainPanel.add(howToTranslate);
        howToTranslate.setBounds(700, 500, 370, 40);

        howToDefine.setFont(new java.awt.Font("Fira Sans", 0, 34)); // NOI18N
        howToDefine.setForeground(new java.awt.Color(255, 255, 255));
        howToDefine.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        howToDefine.setText("How to use Define?");
        howToDefine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        howToDefine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                howToDefineMouseClicked(evt);
            }
        });
        helpMainPanel.add(howToDefine);
        howToDefine.setBounds(700, 420, 320, 40);

        burgerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        burgerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2. Burger Icon.png"))); // NOI18N
        burgerIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        burgerIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                burgerIconMouseClicked(evt);
            }
        });
        helpMainPanel.add(burgerIcon);
        burgerIcon.setBounds(30, 30, 55, 38);

        helpBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1. Help Background.png"))); // NOI18N
        helpBackground.setAlignmentY(0.0F);
        helpMainPanel.add(helpBackground);
        helpBackground.setBounds(0, 0, 1540, 840);

        getContentPane().add(helpMainPanel);
        helpMainPanel.setBounds(0, 0, 1540, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void howToDefineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howToDefineMouseClicked
        // TODO add your handling code here:
        new HelpDefine().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_howToDefineMouseClicked

    private void howToTranslateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_howToTranslateMouseClicked
        // TODO add your handling code here:
        new HelpTranslate().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_howToTranslateMouseClicked

    private void wotdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wotdMouseClicked
        setVisible(false);
        new WordofTheDay().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_wotdMouseClicked

    private void wotdLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wotdLabelMouseClicked
        setVisible(false);
        new WordofTheDay().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_wotdLabelMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        setVisible(false);
        new About().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        setVisible(false);
        new About().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void burgerIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_burgerIconMouseClicked
        setVisible(false);
        new UI().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_burgerIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JLabel burgerIcon;
    private javax.swing.JLabel help;
    private javax.swing.JLabel helpBackground;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JPanel helpMainPanel;
    private javax.swing.JPanel helpSidebar;
    private javax.swing.JLabel howToDefine;
    private javax.swing.JLabel howToTranslate;
    private javax.swing.JLabel sideBar;
    private javax.swing.JLabel wotd;
    private javax.swing.JLabel wotdLabel;
    // End of variables declaration//GEN-END:variables
}
