/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lumen;

import javax.swing.JFrame;

/**
 *
 * @author Hanse
 */
public class HelpTranslate extends javax.swing.JFrame {

    /**
     * Creates new form HelpDefine
     */
    public HelpTranslate() {
        initComponents();
        setLocationRelativeTo(null);
        
        backgroundPt2.setVisible(false);
        forward2.setVisible(false);
        backward2.setVisible(false);
        backgroundPt3.setVisible(false);
        backward3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defineHelpPanel = new javax.swing.JPanel();
        mainBack = new javax.swing.JLabel();
        backward3 = new javax.swing.JLabel();
        backgroundPt3 = new javax.swing.JLabel();
        forward2 = new javax.swing.JLabel();
        backward2 = new javax.swing.JLabel();
        backgroundPt2 = new javax.swing.JLabel();
        forward1 = new javax.swing.JLabel();
        backgroundPt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lumen");
        setMaximumSize(new java.awt.Dimension(1540, 840));
        setMinimumSize(new java.awt.Dimension(1540, 840));
        setPreferredSize(new java.awt.Dimension(1540, 840));
        setResizable(false);
        setSize(new java.awt.Dimension(1540, 840));
        getContentPane().setLayout(null);

        defineHelpPanel.setAlignmentX(0.0F);
        defineHelpPanel.setAlignmentY(0.0F);
        defineHelpPanel.setMaximumSize(new java.awt.Dimension(1540, 840));
        defineHelpPanel.setLayout(null);

        mainBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back_button.png"))); // NOI18N
        mainBack.setAlignmentY(0.0F);
        mainBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainBackMouseClicked(evt);
            }
        });
        defineHelpPanel.add(mainBack);
        mainBack.setBounds(0, 0, 162, 98);

        backward3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help_backward.png"))); // NOI18N
        backward3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backward3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backward3MouseClicked(evt);
            }
        });
        defineHelpPanel.add(backward3);
        backward3.setBounds(1110, 623, 29, 44);

        backgroundPt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1. How to Translate Pt.III Background.png"))); // NOI18N
        defineHelpPanel.add(backgroundPt3);
        backgroundPt3.setBounds(0, 0, 1540, 840);

        forward2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help_forward.png"))); // NOI18N
        forward2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forward2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forward2MouseClicked(evt);
            }
        });
        defineHelpPanel.add(forward2);
        forward2.setBounds(1176, 653, 29, 44);

        backward2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help_backward.png"))); // NOI18N
        backward2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backward2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backward2MouseClicked(evt);
            }
        });
        defineHelpPanel.add(backward2);
        backward2.setBounds(1136, 653, 29, 44);

        backgroundPt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1. How to Translate Pt.II Background.png"))); // NOI18N
        backgroundPt2.setOpaque(true);
        defineHelpPanel.add(backgroundPt2);
        backgroundPt2.setBounds(0, 0, 1540, 840);

        forward1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help_forward.png"))); // NOI18N
        forward1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forward1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forward1MouseClicked(evt);
            }
        });
        defineHelpPanel.add(forward1);
        forward1.setBounds(1230, 614, 29, 44);

        backgroundPt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1. How to Translate Pt.I Background.png"))); // NOI18N
        backgroundPt1.setAlignmentY(0.0F);
        defineHelpPanel.add(backgroundPt1);
        backgroundPt1.setBounds(0, 0, 1540, 840);

        getContentPane().add(defineHelpPanel);
        defineHelpPanel.setBounds(0, 0, 1540, 840);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forward1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forward1MouseClicked
        // TODO add your handling code here:
        backgroundPt1.setVisible(false);
        forward1.setVisible(false);
        backgroundPt2.setVisible(true);
        forward2.setVisible(true);
        backward2.setVisible(true);
    }//GEN-LAST:event_forward1MouseClicked

    private void backward2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backward2MouseClicked
        // TODO add your handling code here:
        backgroundPt1.setVisible(true);
        forward1.setVisible(true);
        backgroundPt2.setVisible(false);
        forward2.setVisible(false);
        backward2.setVisible(false);
    }//GEN-LAST:event_backward2MouseClicked

    private void forward2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forward2MouseClicked
        // TODO add your handling code here:
        backgroundPt3.setVisible(true);
        backward3.setVisible(true);
        backgroundPt2.setVisible(false);
        forward2.setVisible(false);
        backward2.setVisible(false);
    }//GEN-LAST:event_forward2MouseClicked

    private void backward3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backward3MouseClicked
        // TODO add your handling code here:
        backgroundPt2.setVisible(true);
        forward2.setVisible(true);
        backward2.setVisible(true);
        backgroundPt3.setVisible(false);
        backward3.setVisible(false);
    }//GEN-LAST:event_backward3MouseClicked

    private void mainBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainBackMouseClicked
        // TODO add your handling code here:
        new HelpFile().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpTranslate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpTranslate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpTranslate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpTranslate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpTranslate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundPt1;
    private javax.swing.JLabel backgroundPt2;
    private javax.swing.JLabel backgroundPt3;
    private javax.swing.JLabel backward2;
    private javax.swing.JLabel backward3;
    private javax.swing.JPanel defineHelpPanel;
    private javax.swing.JLabel forward1;
    private javax.swing.JLabel forward2;
    private javax.swing.JLabel mainBack;
    // End of variables declaration//GEN-END:variables
}
