package Lumen;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hanse
 */
public class WordofTheDay extends javax.swing.JFrame {

    /**
     * Creates new form WordofTheDay
     */
    public WordofTheDay() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        resWordLbl = new javax.swing.JTextField();
        resType = new javax.swing.JTextField();
        resDfn = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        wotdLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        helpLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lumen");
        setMaximumSize(new java.awt.Dimension(1540, 840));
        setMinimumSize(new java.awt.Dimension(1540, 840));
        setPreferredSize(new java.awt.Dimension(1540, 840));
        setResizable(false);
        setSize(new java.awt.Dimension(1540, 840));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMaximumSize(new java.awt.Dimension(1540, 840));
        jPanel1.setMinimumSize(new java.awt.Dimension(1540, 840));
        jPanel1.setPreferredSize(new java.awt.Dimension(1540, 840));
        jPanel1.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2. Burger Icon.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 30, 55, 38);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3. wotd_header.png"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(320, 130, 510, 100);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(null);

        resWordLbl.setEditable(false);
        resWordLbl.setFont(new java.awt.Font("Fira Sans", 0, 48)); // NOI18N
        resWordLbl.setForeground(new java.awt.Color(255, 255, 255));
        resWordLbl.setBorder(null);
        resWordLbl.setOpaque(false);
        jPanel5.add(resWordLbl);
        resWordLbl.setBounds(0, 0, 500, 80);

        resType.setEditable(false);
        resType.setFont(new java.awt.Font("Fira Sans", 0, 20)); // NOI18N
        resType.setForeground(new java.awt.Color(255, 255, 255));
        resType.setBorder(null);
        resType.setOpaque(false);
        resType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resTypeActionPerformed(evt);
            }
        });
        jPanel5.add(resType);
        resType.setBounds(0, 100, 500, 50);

        resDfn.setEditable(false);
        resDfn.setColumns(20);
        resDfn.setFont(new java.awt.Font("Fira Sans", 0, 20)); // NOI18N
        resDfn.setForeground(new java.awt.Color(255, 255, 255));
        resDfn.setRows(5);
        resDfn.setBorder(null);
        resDfn.setOpaque(false);
        jPanel5.add(resDfn);
        resDfn.setBounds(0, 170, 500, 160);
        resDfn.setLineWrap(true);
        resDfn.setWrapStyleWord(true);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(320, 280, 500, 390);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(380, 100, 1160, 740);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMaximumSize(new java.awt.Dimension(379, 745));
        jPanel2.setMinimumSize(new java.awt.Dimension(379, 744));
        jPanel2.setPreferredSize(new java.awt.Dimension(379, 744));
        jPanel2.setLayout(null);

        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setMaximumSize(new java.awt.Dimension(380, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(380, 100));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(380, 100));
        jPanel4.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3. WoTD Icon.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 19, 56, 56);

        wotdLabel.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        wotdLabel.setForeground(new java.awt.Color(255, 255, 255));
        wotdLabel.setText("Word of the Day");
        wotdLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wotdLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(wotdLabel);
        wotdLabel.setBounds(110, 30, 174, 40);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 40, 380, 100);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel6.setMaximumSize(new java.awt.Dimension(380, 100));
        jPanel6.setMinimumSize(new java.awt.Dimension(380, 100));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(380, 100));
        jPanel6.setLayout(null);

        helpLabel.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        helpLabel.setForeground(new java.awt.Color(255, 255, 255));
        helpLabel.setText("Help");
        helpLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpLabelMouseClicked(evt);
            }
        });
        jPanel6.add(helpLabel);
        helpLabel.setBounds(120, 32, 50, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5. Help Icon.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel7);
        jLabel7.setBounds(30, 20, 56, 56);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 140, 380, 100);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.setMaximumSize(new java.awt.Dimension(380, 100));
        jPanel7.setMinimumSize(new java.awt.Dimension(380, 100));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(380, 100));
        jPanel7.setLayout(null);

        aboutLabel.setFont(new java.awt.Font("Fira Sans", 0, 24)); // NOI18N
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setText("About");
        aboutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
        });
        jPanel7.add(aboutLabel);
        aboutLabel.setBounds(120, 33, 70, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6. About Icon.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel5);
        jLabel5.setBounds(30, 20, 56, 56);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(0, 240, 380, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2. wotd_sidebar.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setMaximumSize(new java.awt.Dimension(379, 744));
        jLabel2.setMinimumSize(new java.awt.Dimension(379, 744));
        jLabel2.setPreferredSize(new java.awt.Dimension(379, 744));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, -6, 380, 750);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 100, 379, 744);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2. Main Menu Sidebar Blur.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(1540, 840));
        jLabel1.setMinimumSize(new java.awt.Dimension(1540, 840));
        jLabel1.setPreferredSize(new java.awt.Dimension(1540, 840));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1540, 840);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1540, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        setVisible(false);
        new UI().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void resTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resTypeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            Connection conn;
            conn = ConnectDB.connectDb();
            ResultSet rs;
            PreparedStatement pst;
            String search = "SELECT words, wordtype, definition FROM dictionary ORDER BY RANDOM() LIMIT 1";
            pst = conn.prepareStatement(search);
            
             rs   = pst.executeQuery();
           //  rs   = stmt.executeQuery(abdicationDfn);
              resWordLbl.setText(rs.getString(1));
              resType.setText(rs.getString(2));
              resDfn.setText(rs.getString(3));
              
        } 
            catch(Exception e){
               
            JOptionPane.showMessageDialog(null, "Sorry, no definition found. Please try another word!", "Lumen", JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }         // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        setVisible(false); 
        new About().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        setVisible(false); 
        new About().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        setVisible(false); 
        new HelpFile().setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void helpLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLabelMouseClicked
        setVisible(false); 
        new HelpFile().setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_helpLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordofTheDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordofTheDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordofTheDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordofTheDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordofTheDay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JLabel helpLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextArea resDfn;
    private javax.swing.JTextField resType;
    private javax.swing.JTextField resWordLbl;
    private javax.swing.JLabel wotdLabel;
    // End of variables declaration//GEN-END:variables
}
